title: "Signal"
author: "Jane"
description: "STATISTICS, ALGORITHMS, DATA STRUCTURE, DATA ENGINEERING, MACHINE LEARNING, DEEP LEARNING, ETC."
more: "read more »"
url: "https://lovesignal.github.io/"
baseurl: ""
paginate: 3
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "lovesignal"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/lovesignal"
  - envelope: "mailto:hmtb.signal@gmail.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]




